### ISSUE TITLE
editing household information from the Profile edit page

### ISSUE THREAD

**Issue by gdylee88** [gather-community/gather#878] opened 2021-08-23 17:51 UTC
It looks like changes to the household section are working, except with the unit field,
Changing the unit information directly from the Household page works.

**Comment by smoyth** [comment] 2021-08-25 13:08
Hi @gdylee88! I am not able to reproduce this bug. Could please provide step by step instructions on how to reproduce this? Thanks!

**Comment by smoyth** [comment] 2021-08-29 03:50
Good catch Godfrey! Should be fixed now. Please try it out.

**Closed by smoyth** 2021-08-29 03:50 UTC
Labels: type:bug, area:people
