### ISSUE TITLE
Ability to place an event on multiple calendars

### ISSUE THREAD

**Issue by leilatite** [gather-community/gather#837] opened 2021-06-29 00:54 UTC
The strong expectation of most Shepherd Village users is that, when they need to reserve a room for a meeting, they could check a box 📦 that would say something like, “Duplicate this reservation on the Meetings calendar”.

To maintain some degree of flexibility, one option would be to display a short list of checkboxes below the reservation detail page under a prompt which would say something like, “Duplicate this reservation as a:”.  The minimal short list of checkboxes would be the two default root source calendars (Meetings and Social Events).

Another option would be to include in the checklist all of the root source calendars (default + additional user-defined root calendars).

Another (even more flexible) option would be to include in the checklist any source calendar(s) in the root of the calendar hierarchy or within any calendar group(s) as administratively configured.

The ability to place an event on multiple calendars 📆, e.g., adding a meeting to a Reservations  calendar and also to the Meetings calendar at the same time, is a higher priority for Shepherd Villlage than adding recurring events.

**Comment by smoyth** [comment] 2021-12-12 22:14
Duplicate of #308

**Closed by smoyth** 2021-12-12 22:14 UTC
Labels: priority:high, type:enhancement, area:reservations, area:calendaring, requester:shepherd-village
